### ISSUE TITLE
Submods Panel Issue Still Not Fixed

### ISSUE THREAD

**Issue by multimokia** [cooliocolophon/MAS-Panic-Button-Submod#1]
https://github.com/cooliocolophon/MAS-Panic-Button-Submod/blob/2c61d00a5d6e28823ad01e97a723afcd0484fc6e/Game/submods/panic_button.rpy#L15-L19

This block still does not address the issue in the submod updater. You need to add a `tag_formatter` to use version tags similar to my submods.
Otherwise this still crashes MAS:

![image](https://user-images.githubusercontent.com/22531674/109842287-eac80080-7c17-11eb-8fd0-204c7a25c64e.png)
(The `v` needs to be sanitized from the string when fetched from GitHub for the submod updater. See documentation for that [here](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin#usage))

**Comment by cooliocolophon** [comment]
Edited both code and tags. Crash should be fixed.
